COPY_DIR = cp -f -R
INSTALL_DIR = $(COPY_DIR)

.PHONY: install uninstall

all:
	# Do nothing. Only concerned with install/uninstall for these headers.

install:
	$(INSTALL_DIR) crete /usr/include/crete
uninstall:
	rm -rf /usr/include/crete
