#!/bin/bash

CRETE_SOURCE_DIR=$1
CRETE_BINARY_DIR=$2

make ENABLE_OPTIMIZED=1 LDFLAGS=-L$CRETE_BINARY_DIR/bin CXXFLAGS="-I$CRETE_SOURCE_DIR/lib/include -I$CRETE_SOURCE_DIR/front-end/qemu-1.0 -I$CRETE_SOURCE_DIR/front-end/qemu-1.0/fpu" -j7
